# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - master

env:
  AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
  CHANNEL_ID: ${{secrets.CHANNEL_ID}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: execute
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm run esm
